import { dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { FlatCompat } from '@eslint/eslintrc'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

// FlatCompat bridges the legacy `extends` array on `eslint-config-next` to
// the new flat-config format that ESLint 9 expects. Once
// `eslint-config-next` ships a native flat config we can drop FlatCompat
// and just `import next from 'eslint-config-next'` directly.
const compat = new FlatCompat({ baseDirectory: __dirname })

const config = [
  ...compat.extends('next/core-web-vitals'),
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'next-env.d.ts',
      // generated by `next dev` / `next build` — not source code we lint.
      '.turbo/**',
    ],
  },
]

export default config
